[project]
name = "tinylm"
version = "0.1.0"
description = "Transformers but for tinygrad"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "numpy>=2.2.6",
  "tinygrad",
]
license = { file = "LICENSE" }
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: GPU",
  "Environment :: MacOS X",
  "Framework :: FastAPI",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Typing :: Typed",
]

[project.urls]
homepage = "https://github.com/neodyland/tinylm"
issues = "https://github.com/neodyland/tinylm/issues"

[project.optional-dependencies]
all = [
  "tinylm[cli]",
  "tinylm[hf]",
  "tinylm[api]",
  "tinylm[audio]",
]
api = [
  "tinylm[cli]",
  "fastapi>=0.115.12",
  "uvicorn>=0.34.2",
  "openai>=1.82.0",
  "pydantic>=2.11.5",
]
audio = [
  "pydub>=0.25.1",
  "audioop-lts>=0.2.1",
]
cli = ["typer>=0.16.0", "rich>=14.0.0", "tinylm[hf]"]
hf = [
  "huggingface-hub>=0.32.0",
  "jinja2>=3.1.6",
  "transformers>=4.52.3",
]
test = [
  "torch>=2.7.1",
  "torchaudio>=2.7.1",
  "pytest>=8.4.1",
  "pytest-xdist>=3.7.0",
]

[dependency-groups]
dev = [
  "poethepoet>=0.42.0",
  "ruff>=0.11.10",
  "tombi>=0.7.32",
  "ty>=0.0.1a6",
]

[tool.poe.tasks]
format.shell = "ruff format . && tombi format ."
lint.shell = "ruff check . && tombi check ."

[tool.uv.sources]
tinygrad = { git = "https://github.com/tinygrad/tinygrad" }
